server:
  port: 8888
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://172.26.223.28:3306/test_1?useUnicode=true&characterEncoding=utf8
        username: mysqladmin
        password: MPadmin
    application:
      name: consume-service

mybatis:
  type-aliases-package: com.happylifeplat.transaction.tx.dubbo.sample.consume.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.happylifeplat.bonuspoint: info
        com.happylifeplat.lottery: debug
        com.happylifeplat: debug
        io.netty: info

    path: "./logs"


